### PR TITLE
GH-44950: My WIP changes for Rtools

### PR DESCRIPTION
**Pull request by amoeba**
This isn't quite done yet but these changes make aws_c_common build for me.

Ref: https://github.com/apache/arrow/pull/44989

### CODE REVIEW

**Comment by amoeba** [comment]
I'll keep working on this and push changes here.

**Comment by amoeba** [comment]
Hey @raulcd, I have a working set of patches now. This PR needs at least two more things, maybe both of which I could use help on:

1. I think we want to guard applying the patches so they're only applied when we're doing the Rtools40 build. Maybe an environment variable?
2. The build step succeeds but I think the pkg step can sometimes fail, so I need to run this locally a couple more times to make sure it's solid.

**Review by raulcd — APPROVED** [review]
Thanks @amoeba ! I am merging this to my branch to continue investigating there!

**Comment by raulcd** [comment]
I am trying to apply the patch but I am having some issues like:
```
D:/a/arrow/arrow/src/build-x86_64-cpp/aws_c_io_ep-prefix/src/aws_c_io_ep/source/windows/secure_channel_tls_handler.c:59:14: error: redeclaration of 'enum _SEC_APPLICATION_PROTOCOL_NEGOTIATION_EXT'
   59 | typedef enum _SEC_APPLICATION_PROTOCOL_NEGOTIATION_EXT {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/rtools40/ucrt64/x86_64-w64-mingw32/include/security.h:40,
                 from D:/a/arrow/arrow/src/build-x86_64-cpp/aws_c_io_ep-prefix/src/aws_c_io_ep/source/windows/secure_channel_tls_handler.c:25:
C:/rtools40/ucrt64/x86_64-w64-mingw32/include/sspi.h:251:16: note: originally defined here
  251 |   typedef enum _SEC_APPLICATION_PROTOCOL_NEGOTIATION_EXT {
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/arrow/arrow/src/build-x86_64-cpp/aws_c_io_ep-prefix/src/aws_c_io_ep/source/windows/secure_channel_tls_handler.c:60:5: error: redeclaration of enumerator 'SecApplicationProtocolNegotiationExt_None'
   60 |     SecApplicationProtocolNegotiationExt_None,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/rtools40/ucrt64/x86_64-w64-mingw32/include/security.h:40,
                 from D:/a/arrow/arrow/src/build-x86_64-cpp/aws_c_io_ep-prefix/src/aws_c_io_ep/source/windows/secure_channel_tls_handler.c:25:
C:/rtools40/ucrt64/x86_64-w64-mingw32/include/sspi.h:252:5: note: previous definition of 'SecApplicationProtocolNegotiationExt_None' was here
  252 |     SecApplicationProtocolNegotiationExt_None,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/arrow/arrow/src/build-x86_64-cpp/aws_c_io_ep-prefix/src/aws_c_io_ep/source/windows/secure_channel_tls_handler.c:61:5: error: redeclaration of enumerator 'SecApplicationProtocolNegotiationExt_NPN'
   61 |     SecApplicationProtocolNegotiationExt_NPN,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/rtools40/ucrt64/x86_64-w64-mingw32/include/security.h:40,
```
I am trying to manually fix the patch on the main repo

**Pull request merged**
